# Generated by Django 4.1.7 on 2023-04-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('PRO', 'pro'), ('ING', 'ing')], default='pro', max_length=255),
        ),
    ]
