# Generated by Django 4.1.7 on 2023-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredients_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienteproducto',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
