# Generated by Django 4.1.7 on 2023-04-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categorytype'),
        ('ingredients', '0003_remove_ingredienteproducto_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='IngredienteProducto',
        ),
    ]
