# Generated by Django 4.1.7 on 2023-04-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('ingredients', '0004_remove_ingredients_name_ingredients_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedores'),
        ),
    ]
