# Generated by Django 4.1.7 on 2023-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredients_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
