# Generated by Django 4.1.7 on 2023-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_ingredients_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='um',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
