# Generated by Django 4.1.7 on 2023-03-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tables', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='codOrder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
