# Generated by Django 4.1.7 on 2023-03-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='codOrder',
        ),
        migrations.RemoveField(
            model_name='table',
            name='product',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
