# Generated by Django 4.1.7 on 2023-05-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_active'),
        ('ingredients', '0009_remove_ingredients_quantity_ingredients_um'),
        ('ingredienteProducto', '0002_rename_idingrediente_ingredienteproducto_idingrediente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredienteproducto',
            unique_together={('idProducto', 'idIngrediente')},
        ),
    ]
