# Generated by Django 4.1.7 on 2023-03-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'delivered'), ('PENDING', 'pending')], max_length=255),
        ),
    ]
