# Generated by Django 4.1.7 on 2023-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_codpedido_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='codPedido',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered')], max_length=255),
        ),
    ]
