# Generated by Django 4.1.7 on 2023-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('PRO', 'pro'), ('ING', 'ing')], max_length=255, null=True),
        ),
    ]
