# Generated by Django 4.1.7 on 2023-03-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('PRO', 'pro'), ('ING', 'ing')], default='pro', max_length=255),
        ),
    ]
