# Generated by Django 4.1.7 on 2023-04-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ingrediente_ingredienteproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienteproducto',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredienteproducto',
            name='product',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='IngredienteProducto',
        ),
    ]
