# Generated by Django 4.1.7 on 2023-04-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_ingredienteproducto_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productType',
        ),
    ]
