# Generated by Django 4.1.7 on 2023-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_remove_ingredients_quantity_ingredients_um'),
        ('ingredienteProducto', '0001_initial'),
        ('products', '0006_remove_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(through='ingredienteProducto.IngredienteProducto', to='ingredients.ingredients'),
        ),
    ]
